<?xml version="1.0" encoding="utf-8"?><Database Name="CompanyProducts" Class="CompanyProductsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HPSPECTRE;Initial Catalog=CompanyProducts;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CompanyProductsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CompanyProducts" Member="CompanyProducts">
    <Type Name="CompanyProduct">
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BrandName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModelName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(19,4) NOT NULL" CanBeNull="false" />
      <Column Name="SKU" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Feature1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Feature2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>